#!/usr/bin/env bash
# File: plant
# Author: Matt Manzi
# Date: 2020-11-14
#
# In Programmer Jargon:
# Install application configurations and update your *rc file to load shell
# scripts on session start-up.
#
# In Fig Tree Jargon:
# Plant perennials and prepare your garden for annuals.


# set FIG_HOME to current directory
export FIG_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


#### Includes
source "${FIG_HOME}/tool-shed/logger.bash"
source "${FIG_HOME}/tool-shed/parse_noseed.bash"


#### Globals


#### Main Script

# parse the noseed file
parseNoseedFile

# plant perennials
__perennialsDir="${FIG_HOME}/perennials"
for perennial in "${__perennialsDir}"/*; do
    logTrace "Evaluating perennial: ${perennial}"

    if [[ ! " ${__noSeed[@]} " =~ " ${perennial}".*" " ]]; then
        logInfo "Planting perennial: ${perennial}"
        
        # provided.sh are the template file names but this will plant any script file
        "${perennial}"/*".sh"
    else
        logDebug "Skipping perennial: ${perennial}"
    fi
done

# install the tend script
logInfo "Installing tend script for bash"
echo "export FIG_HOME=\"$( cd \"$( dirname \"${BASH_SOURCE[0]}\" )\" && pwd )\"
source \"${FIG_HOME}/annuals/tend.bashrc\"" >> "${HOME}/.bashrc
"

logInfo "Installing tend script for zsh"
echo "export FIG_HOME=\"$( cd \"$( dirname \"${BASH_SOURCE[0]}\" )\" && pwd )\"
source \"${FIG_HOME}/annuals/tend.zshrc\"" >> "${HOME}/.zshrc
"
