#!/usr/bin/env bash
# File: plant
# Author: Matt Manzi
# Date: 2020-11-14
#
# In Programmer Jargon:
# Install application configurations and update your *rc file to load shell
# scripts on session start-up.
#
# In Fig Tree Jargon:
# Plant perennials and prepare your garden for annuals.


# set FIG_HOME to current directory
export FIG_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


#### Includes
source "${FIG_HOME}/tool-shed/logger.bash"
source "${FIG_HOME}/tool-shed/parse_noseed.bash"


#### Main Script

# parse the noseed file
parseNoseedFile

# plant perennials
__perennialsDir="${FIG_HOME}/perennials"
for perennial in "${__perennialsDir}"/*; do
    logTrace "Evaluating perennial: ${perennial}"

    if [[ ! " ${__noSeed[@]} " =~ " ${perennial}".*" " ]]; then
        logInfo "Planting perennial: ${perennial}"
        
        # provided.sh are the template file names but this will plant any script file
        "${perennial}"/*".sh"
    else
        logDebug "Skipping perennial: ${perennial}"
    fi
done

__tendInstall () {
    echo "
export FIG_HOME=\"$FIG_HOME\"
source \"\${FIG_HOME}/annuals/tend$1\"
"
}

# install the tend script for Bash
logInfo "Installing tend script for Bash"
__bashrc=".bashrc"
__tendInstallBash="$(__tendInstall "$__bashrc")"

if ! grep -q 'source "${FIG_HOME' "${HOME}/$__bashrc" &> /dev/null; then
    logDebug "Bash tend script is not already sourced"
    echo "$__tendInstallBash" >> "${HOME}/$__bashrc"
else
    logDebug "Bash tend script is already sourced"
fi

# install the tend script for Zsh
logInfo "Installing tend script for Zsh"
__zshrc=".zshrc"
__tendInstallZsh="$(__tendInstall "$__zshrc")"

if ! grep -q 'source "${FIG_HOME' "${HOME}/$__zshrc" &> /dev/null; then
    logDebug "Zsh tend script is not already sourced"
    echo "${__tendInstallZsh}" >> "${HOME}/$__zshrc"
else
    logDebug "Zsh tend script is already sourced"
fi
